In [1]:
import pandas as pd

In [2]:
# Create customers DataFrame
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "customer_name": ["Anil", "Priya", "Rahul", "Sneha"],
    "city": ["Bengaluru", "Mumbai", "Delhi", "Chennai"]
})

# Create orders DataFrame
orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105],
    "customer_id": [1, 2, 1, 3, 5],
    "product": ["Laptop", "Phone", "Monitor", "Chair", "Table"],
    "amount": [55000, 40000, 30000, 12000, 25000]
})

print("Customers DataFrame:")
display(customers)

print("Orders DataFrame:")
display(orders)

Customers DataFrame:

   customer_id customer_name       city
0            1          Anil  Bengaluru
1            2         Priya     Mumbai
2            3         Rahul      Delhi
3            4         Sneha    Chennai

Orders DataFrame:

   order_id  customer_id  product  amount
0       101            1   Laptop   55000
1       102            2    Phone   40000
2       103            1  Monitor   30000
3       104            3    Chair   12000
4       105            5    Table   25000

In [3]:
# 1. INNER JOIN
inner_join = pd.merge(
    customers,
    orders,
    on="customer_id",
    how="inner"
)

print("1. INNER JOIN")
display(inner_join)


# 2. LEFT JOIN
left_join = pd.merge(
    customers,
    orders,
    on="customer_id",
    how="left"
)

print("2. LEFT JOIN")
display(left_join)


# 3. RIGHT JOIN
right_join = pd.merge(
    customers,
    orders,
    on="customer_id",
    how="right"
)

print("3. RIGHT JOIN")
display(right_join)


# 4. OUTER JOIN
outer_join = pd.merge(
    customers,
    orders,
    on="customer_id",
    how="outer"
)

print("4. OUTER JOIN")
display(outer_join)

1. INNER JOIN

   customer_id customer_name       city  order_id  product  amount
0            1          Anil  Bengaluru       101   Laptop   55000
1            1          Anil  Bengaluru       103  Monitor   30000
2            2         Priya     Mumbai       102    Phone   40000
3            3         Rahul      Delhi       104    Chair   12000

2. LEFT JOIN

   customer_id customer_name       city  order_id  product   amount
0            1          Anil  Bengaluru     101.0   Laptop  55000.0
1            1          Anil  Bengaluru     103.0  Monitor  30000.0
2            2         Priya     Mumbai     102.0    Phone  40000.0
3            3         Rahul      Delhi     104.0    Chair  12000.0
4            4         Sneha    Chennai       NaN      NaN      NaN

3. RIGHT JOIN

   customer_id customer_name       city  order_id  product  amount
0            1          Anil  Bengaluru       101   Laptop   55000
1            2         Priya     Mumbai       102    Phone   40000
2            1          Anil  Bengaluru       103  Monitor   30000
3            3         Rahul      Delhi       104    Chair   12000
4            5           NaN        NaN       105    Table   25000

4. OUTER JOIN

   customer_id customer_name       city  order_id  product   amount
0            1          Anil  Bengaluru     101.0   Laptop  55000.0
1            1          Anil  Bengaluru     103.0  Monitor  30000.0
2            2         Priya     Mumbai     102.0    Phone  40000.0
3            3         Rahul      Delhi     104.0    Chair  12000.0
4            4         Sneha    Chennai       NaN      NaN      NaN
5            5           NaN        NaN     105.0    Table  25000.0

In [4]:
# 5. PIVOT TABLE - Sales by Region and Product

sales_data = pd.DataFrame({
    "region": ["South", "South", "North", "North", "West", "West"],
    "product": ["Laptop", "Phone", "Laptop", "Phone", "Laptop", "Phone"],
    "amount": [55000, 40000, 65000, 30000, 75000, 45000]
})

print("Sales Data:")
display(sales_data)

pivot_table = pd.pivot_table(
    sales_data,
    values="amount",
    index="region",
    columns="product",
    aggfunc="sum",
    fill_value=0
)

print("Pivot Table - Sales by Region and Product:")
display(pivot_table)

Sales Data:

  region product  amount
0  South  Laptop   55000
1  South   Phone   40000
2  North  Laptop   65000
3  North   Phone   30000
4   West  Laptop   75000
5   West   Phone   45000

Pivot Table - Sales by Region and Product:

product  Laptop  Phone
region
North     65000  30000
South     55000  40000
West      75000  45000

In [5]:
# 6. MELT - Convert Wide Data to Long Format

wide_data = pd.DataFrame({
    "region": ["North", "South", "West"],
    "Laptop": [65000, 55000, 75000],
    "Phone": [30000, 40000, 45000]
})

print("Wide Data:")
display(wide_data)

long_data = pd.melt(
    wide_data,
    id_vars=["region"],
    var_name="product",
    value_name="sales"
)

print("Melted Data - Long Format:")
display(long_data)

Wide Data:

  region  Laptop  Phone
0  North   65000  30000
1  South   55000  40000
2   West   75000  45000

Melted Data - Long Format:

  region product  sales
0  North  Laptop  65000
1  South  Laptop  55000
2   West  Laptop  75000
3  North   Phone  30000
4  South   Phone  40000
5   West   Phone  45000

In [6]:
# 7. METHOD CHAINING - Multiple Pandas Operations

result = (
    sales_data
    .query("amount > 40000")
    .groupby("region", as_index=False)["amount"]
    .sum()
    .sort_values("amount", ascending=False)
)

print("Method Chaining - Sales Above 40000:")
display(result)

Method Chaining - Sales Above 40000:

  region  amount
2   West  120000
0  North   65000
1  South   55000